<?php
/** @noinspection PhpUnhandledExceptionInspection
 * @noinspection PhpMissingParamTypeInspection
 * @noinspection ClassConstantCanBeUsedInspection
 */
/* -- CONFIG START HERE --
{
    "rooturl": ".",
    "fileGen": ".",
    "savefile": "1",
    "compression": "1",
    "savefileName": "autoload.php",
    "excludeNS": "",
    "excludePath": "",
    "externalPath": ""
}
-- CONFIG END HERE -- */

/**
 * This class is used for autocomplete.
 * Class _AUTOLOAD_
 * @noautoload it avoids to index this class
 * @generated by AutoLoadOne 1.26 generated 2022/05/11 11:44:18
 * @copyright Copyright Jorge Castro C - MIT License. https://github.com/EFTEC/AutoLoadOne
 */
/** @var bool $autoloadone__debug if true then in case of error, it shows more information about the source of it  */ 
$autoloadone__debug = true;

/* @var string[] Where $_arrautoloadCustom['namespace\Class']='folder\file.php' */
$s627ba192388d7__arrautoloadCustom = [
	'DS\UrlFormatter' => '/app/classes/router/UrlFormatter.php',
	'ComposerAutoloaderInit98547fe9d98c94ce833c511251109d7c' => '|1|real.php',
	'Composer\Autoload\ComposerStaticInit98547fe9d98c94ce833c511251109d7c' => '|1|static.php',
	'Klein\Tests\HttpStatusTests' => '|2|HttpStatusTest.php',
	'Klein\Tests\ResponsesTest' => '|2|ResponseTest.php',
	'PharIo\Manifest\ElementCollectionException' => '|3|lementCollectionException.php',
	'PharIo\Manifest\Exception' => '|3|xception.php',
	'PharIo\Manifest\InvalidApplicationNameException' => '|4|InvalidApplicationNameException.php',
	'PharIo\Manifest\InvalidEmailException' => '|4|InvalidEmailException.php',
	'PharIo\Manifest\InvalidUrlException' => '|4|InvalidUrlException.php',
	'PharIo\Manifest\ManifestDocumentException' => '|4|ManifestDocumentException.php',
	'PharIo\Manifest\ManifestDocumentLoadingException' => '|4|ManifestDocumentLoadingException.php',
	'PharIo\Manifest\ManifestDocumentMapperException' => '|4|ManifestDocumentMapperException.php',
	'PharIo\Manifest\ManifestElementException' => '|4|ManifestElementException.php',
	'PharIo\Manifest\ManifestLoaderException' => '|4|ManifestLoaderException.php',
	'PharIo\Manifest\Application' => '|5|values/Application.php',
	'PharIo\Manifest\ApplicationName' => '|5|values/ApplicationName.php',
	'PharIo\Manifest\Author' => '|5|values/Author.php',
	'PharIo\Manifest\AuthorCollection' => '|5|values/AuthorCollection.php',
	'PharIo\Manifest\AuthorCollectionIterator' => '|5|values/AuthorCollectionIterator.php',
	'PharIo\Manifest\BundledComponent' => '|5|values/BundledComponent.php',
	'PharIo\Manifest\BundledComponentCollection' => '|5|values/BundledComponentCollection.php',
	'PharIo\Manifest\BundledComponentCollectionIterator' => '|5|values/BundledComponentCollectionIterator.php',
	'PharIo\Manifest\CopyrightInformation' => '|5|values/CopyrightInformation.php',
	'PharIo\Manifest\Email' => '|5|values/Email.php',
	'PharIo\Manifest\Extension' => '|5|values/Extension.php',
	'PharIo\Manifest\Library' => '|5|values/Library.php',
	'PharIo\Manifest\License' => '|5|values/License.php',
	'PharIo\Manifest\Manifest' => '|5|values/Manifest.php',
	'PharIo\Manifest\PhpExtensionRequirement' => '|5|values/PhpExtensionRequirement.php',
	'PharIo\Manifest\PhpVersionRequirement' => '|5|values/PhpVersionRequirement.php',
	'PharIo\Manifest\Requirement' => '|5|values/Requirement.php',
	'PharIo\Manifest\RequirementCollection' => '|5|values/RequirementCollection.php',
	'PharIo\Manifest\RequirementCollectionIterator' => '|5|values/RequirementCollectionIterator.php',
	'PharIo\Manifest\Type' => '|5|values/Type.php',
	'PharIo\Manifest\Url' => '|5|values/Url.php',
	'PharIo\Manifest\AuthorElement' => '|5|xml/AuthorElement.php',
	'PharIo\Manifest\AuthorElementCollection' => '|5|xml/AuthorElementCollection.php',
	'PharIo\Manifest\BundlesElement' => '|5|xml/BundlesElement.php',
	'PharIo\Manifest\ComponentElement' => '|5|xml/ComponentElement.php',
	'PharIo\Manifest\ComponentElementCollection' => '|5|xml/ComponentElementCollection.php',
	'PharIo\Manifest\ContainsElement' => '|5|xml/ContainsElement.php',
	'PharIo\Manifest\CopyrightElement' => '|5|xml/CopyrightElement.php',
	'PharIo\Manifest\ElementCollection' => '|5|xml/ElementCollection.php',
	'PharIo\Manifest\ExtElement' => '|5|xml/ExtElement.php',
	'PharIo\Manifest\ExtElementCollection' => '|5|xml/ExtElementCollection.php',
	'PharIo\Manifest\ExtensionElement' => '|5|xml/ExtensionElement.php',
	'PharIo\Manifest\LicenseElement' => '|5|xml/LicenseElement.php',
	'PharIo\Manifest\ManifestDocument' => '|5|xml/ManifestDocument.php',
	'PharIo\Manifest\ManifestElement' => '|5|xml/ManifestElement.php',
	'PharIo\Manifest\PhpElement' => '|5|xml/PhpElement.php',
	'PharIo\Manifest\RequiresElement' => '|5|xml/RequiresElement.php',
	'PharIo\Version\AbstractVersionConstraint' => '|6|version/src/constraints/AbstractVersionConstraint.php',
	'PharIo\Version\AndVersionConstraintGroup' => '|6|version/src/constraints/AndVersionConstraintGroup.php',
	'PharIo\Version\AnyVersionConstraint' => '|6|version/src/constraints/AnyVersionConstraint.php',
	'PharIo\Version\ExactVersionConstraint' => '|6|version/src/constraints/ExactVersionConstraint.php',
	'PharIo\Version\GreaterThanOrEqualToVersionConstraint' => '|6|version/src/constraints/GreaterThanOrEqualToVersionConstraint.php',
	'PharIo\Version\OrVersionConstraintGroup' => '|6|version/src/constraints/OrVersionConstraintGroup.php',
	'PharIo\Version\SpecificMajorAndMinorVersionConstraint' => '|6|version/src/constraints/SpecificMajorAndMinorVersionConstraint.php',
	'PharIo\Version\SpecificMajorVersionConstraint' => '|6|version/src/constraints/SpecificMajorVersionConstraint.php',
	'PharIo\Version\VersionConstraint' => '|6|version/src/constraints/VersionConstraint.php',
	'PharIo\Version\Exception' => '|6|version/src/exceptions/Exception.php',
	'PharIo\Version\InvalidPreReleaseSuffixException' => '|6|version/src/exceptions/InvalidPreReleaseSuffixException.php',
	'PharIo\Version\InvalidVersionException' => '|6|version/src/exceptions/InvalidVersionException.php',
	'PharIo\Version\NoBuildMetaDataException' => '|6|version/src/exceptions/NoBuildMetaDataException.php',
	'PharIo\Version\NoPreReleaseSuffixException' => '|6|version/src/exceptions/NoPreReleaseSuffixException.php',
	'PharIo\Version\UnsupportedVersionConstraintException' => '|6|version/src/exceptions/UnsupportedVersionConstraintException.php',
	'phpDocumentor\Reflection\DocBlock' => '|7|.php',
	'phpDocumentor\Reflection\DocBlockFactory' => '|7|Factory.php',
	'phpDocumentor\Reflection\DocBlockFactoryInterface' => '|7|FactoryInterface.php',
	'phpDocumentor\Reflection\Utils' => '|8|documentor/reflection-docblock/src/Utils.php',
	'phpDocumentor\Reflection\FqsenResolver' => '|8|documentor/type-resolver/src/FqsenResolver.php',
	'phpDocumentor\Reflection\PseudoType' => '|8|documentor/type-resolver/src/PseudoType.php',
	'phpDocumentor\Reflection\Type' => '|8|documentor/type-resolver/src/Type.php',
	'phpDocumentor\Reflection\TypeResolver' => '|8|documentor/type-resolver/src/TypeResolver.php',
	'SebastianBergmann\CodeCoverage\BranchAndPathCoverageNotSupportedException' => '|8|unit/php-code-coverage/src/Exception/BranchAndPathCoverageNotSupportedException.php',
	'SebastianBergmann\CodeCoverage\DeadCodeDetectionNotSupportedException' => '|8|unit/php-code-coverage/src/Exception/DeadCodeDetectionNotSupportedException.php',
	'SebastianBergmann\CodeCoverage\Exception' => '|8|unit/php-code-coverage/src/Exception/Exception.php',
	'SebastianBergmann\CodeCoverage\InvalidArgumentException' => '|8|unit/php-code-coverage/src/Exception/InvalidArgumentException.php',
	'SebastianBergmann\CodeCoverage\NoCodeCoverageDriverAvailableException' => '|8|unit/php-code-coverage/src/Exception/NoCodeCoverageDriverAvailableException.php',
	'SebastianBergmann\CodeCoverage\NoCodeCoverageDriverWithPathCoverageSupportAvailableException' => '|8|unit/php-code-coverage/src/Exception/NoCodeCoverageDriverWithPathCoverageSupportAvailableException.php',
	'SebastianBergmann\CodeCoverage\ParserException' => '|8|unit/php-code-coverage/src/Exception/ParserException.php',
	'SebastianBergmann\CodeCoverage\Driver\PathExistsButIsNotDirectoryException' => '|8|unit/php-code-coverage/src/Exception/PathExistsButIsNotDirectoryException.php',
	'SebastianBergmann\CodeCoverage\Driver\PcovNotAvailableException' => '|8|unit/php-code-coverage/src/Exception/PcovNotAvailableException.php',
	'SebastianBergmann\CodeCoverage\Driver\PhpdbgNotAvailableException' => '|8|unit/php-code-coverage/src/Exception/PhpdbgNotAvailableException.php',
	'SebastianBergmann\CodeCoverage\ReflectionException' => '|8|unit/php-code-coverage/src/Exception/ReflectionException.php',
	'SebastianBergmann\CodeCoverage\ReportAlreadyFinalizedException' => '|8|unit/php-code-coverage/src/Exception/ReportAlreadyFinalizedException.php',
	'SebastianBergmann\CodeCoverage\StaticAnalysisCacheNotConfiguredException' => '|8|unit/php-code-coverage/src/Exception/StaticAnalysisCacheNotConfiguredException.php',
	'SebastianBergmann\CodeCoverage\TestIdMissingException' => '|8|unit/php-code-coverage/src/Exception/TestIdMissingException.php',
	'SebastianBergmann\CodeCoverage\UnintentionallyCoveredCodeException' => '|8|unit/php-code-coverage/src/Exception/UnintentionallyCoveredCodeException.php',
	'SebastianBergmann\CodeCoverage\Driver\WriteOperationFailedException' => '|8|unit/php-code-coverage/src/Exception/WriteOperationFailedException.php',
	'SebastianBergmann\CodeCoverage\Driver\WrongXdebugVersionException' => '|8|unit/php-code-coverage/src/Exception/WrongXdebugVersionException.php',
	'SebastianBergmann\CodeCoverage\Driver\Xdebug2NotEnabledException' => '|8|unit/php-code-coverage/src/Exception/Xdebug2NotEnabledException.php',
	'SebastianBergmann\CodeCoverage\Driver\Xdebug3NotEnabledException' => '|8|unit/php-code-coverage/src/Exception/Xdebug3NotEnabledException.php',
	'SebastianBergmann\CodeCoverage\Driver\XdebugNotAvailableException' => '|8|unit/php-code-coverage/src/Exception/XdebugNotAvailableException.php',
	'SebastianBergmann\CodeCoverage\XmlException' => '|8|unit/php-code-coverage/src/Exception/XmlException.php',
	'SebastianBergmann\CodeCoverage\Report\Html\Dashboard' => '|8|unit/php-code-coverage/src/Report/Html/Renderer/Dashboard.php',
	'SebastianBergmann\CodeCoverage\Report\Html\Directory' => '|8|unit/php-code-coverage/src/Report/Html/Renderer/Directory.php',
	'SebastianBergmann\CodeCoverage\Report\Html\File' => '|8|unit/php-code-coverage/src/Report/Html/Renderer/File.php',
	'SebastianBergmann\CodeCoverage\Util\Filesystem' => '|8|unit/php-code-coverage/src/Util/Filesystem.php',
	'SebastianBergmann\CodeCoverage\Util\Percentage' => '|8|unit/php-code-coverage/src/Util/Percentage.php',
	'SebastianBergmann\Invoker\Exception' => '|8|unit/php-invoker/src/exceptions/Exception.php',
	'SebastianBergmann\Invoker\ProcessControlExtensionNotLoadedException' => '|8|unit/php-invoker/src/exceptions/ProcessControlExtensionNotLoadedException.php',
	'SebastianBergmann\Invoker\TimeoutException' => '|8|unit/php-invoker/src/exceptions/TimeoutException.php',
	'SebastianBergmann\Template\Exception' => '|8|unit/php-text-template/src/exceptions/Exception.php',
	'SebastianBergmann\Template\InvalidArgumentException' => '|8|unit/php-text-template/src/exceptions/InvalidArgumentException.php',
	'SebastianBergmann\Template\RuntimeException' => '|8|unit/php-text-template/src/exceptions/RuntimeException.php',
	'SebastianBergmann\Timer\Exception' => '|8|unit/php-timer/src/exceptions/Exception.php',
	'SebastianBergmann\Timer\NoActiveTimerException' => '|8|unit/php-timer/src/exceptions/NoActiveTimerException.php',
	'SebastianBergmann\Timer\TimeSinceStartOfRequestNotAvailableException' => '|8|unit/php-timer/src/exceptions/TimeSinceStartOfRequestNotAvailableException.php',
	'PHPUnit\Framework\Constraint\Callback' => '|8|unit/phpunit/src/Framework/Constraint/Callback.php',
	'PHPUnit\Framework\Constraint\Count' => '|8|unit/phpunit/src/Framework/Constraint/Cardinality/Count.php',
	'PHPUnit\Framework\Constraint\GreaterThan' => '|8|unit/phpunit/src/Framework/Constraint/Cardinality/GreaterThan.php',
	'PHPUnit\Framework\Constraint\IsEmpty' => '|8|unit/phpunit/src/Framework/Constraint/Cardinality/IsEmpty.php',
	'PHPUnit\Framework\Constraint\LessThan' => '|8|unit/phpunit/src/Framework/Constraint/Cardinality/LessThan.php',
	'PHPUnit\Framework\Constraint\SameSize' => '|8|unit/phpunit/src/Framework/Constraint/Cardinality/SameSize.php',
	'PHPUnit\Framework\Constraint\Constraint' => '|8|unit/phpunit/src/Framework/Constraint/Constraint.php',
	'PHPUnit\Framework\Constraint\IsEqual' => '|8|unit/phpunit/src/Framework/Constraint/Equality/IsEqual.php',
	'PHPUnit\Framework\Constraint\IsEqualCanonicalizing' => '|8|unit/phpunit/src/Framework/Constraint/Equality/IsEqualCanonicalizing.php',
	'PHPUnit\Framework\Constraint\IsEqualIgnoringCase' => '|8|unit/phpunit/src/Framework/Constraint/Equality/IsEqualIgnoringCase.php',
	'PHPUnit\Framework\Constraint\IsEqualWithDelta' => '|8|unit/phpunit/src/Framework/Constraint/Equality/IsEqualWithDelta.php',
	'PHPUnit\Framework\Constraint\Exception' => '|8|unit/phpunit/src/Framework/Constraint/Exception/Exception.php',
	'PHPUnit\Framework\Constraint\ExceptionCode' => '|8|unit/phpunit/src/Framework/Constraint/Exception/ExceptionCode.php',
	'PHPUnit\Framework\Constraint\ExceptionMessage' => '|8|unit/phpunit/src/Framework/Constraint/Exception/ExceptionMessage.php',
	'PHPUnit\Framework\Constraint\ExceptionMessageRegularExpression' => '|8|unit/phpunit/src/Framework/Constraint/Exception/ExceptionMessageRegularExpression.php',
	'PHPUnit\Framework\Constraint\DirectoryExists' => '|8|unit/phpunit/src/Framework/Constraint/Filesystem/DirectoryExists.php',
	'PHPUnit\Framework\Constraint\FileExists' => '|8|unit/phpunit/src/Framework/Constraint/Filesystem/FileExists.php',
	'PHPUnit\Framework\Constraint\IsReadable' => '|8|unit/phpunit/src/Framework/Constraint/Filesystem/IsReadable.php',
	'PHPUnit\Framework\Constraint\IsWritable' => '|8|unit/phpunit/src/Framework/Constraint/Filesystem/IsWritable.php',
	'PHPUnit\Framework\Constraint\IsAnything' => '|8|unit/phpunit/src/Framework/Constraint/IsAnything.php',
	'PHPUnit\Framework\Constraint\IsIdentical' => '|8|unit/phpunit/src/Framework/Constraint/IsIdentical.php',
	'PHPUnit\Framework\Constraint\JsonMatches' => '|8|unit/phpunit/src/Framework/Constraint/JsonMatches.php',
	'PHPUnit\Framework\Constraint\JsonMatchesErrorMessageProvider' => '|8|unit/phpunit/src/Framework/Constraint/JsonMatchesErrorMessageProvider.php',
	'PHPUnit\Framework\Constraint\IsFinite' => '|8|unit/phpunit/src/Framework/Constraint/Math/IsFinite.php',
	'PHPUnit\Framework\Constraint\IsInfinite' => '|8|unit/phpunit/src/Framework/Constraint/Math/IsInfinite.php',
	'PHPUnit\Framework\Constraint\IsNan' => '|8|unit/phpunit/src/Framework/Constraint/Math/IsNan.php',
	'PHPUnit\Framework\Constraint\ClassHasAttribute' => '|8|unit/phpunit/src/Framework/Constraint/Object/ClassHasAttribute.php',
	'PHPUnit\Framework\Constraint\ClassHasStaticAttribute' => '|8|unit/phpunit/src/Framework/Constraint/Object/ClassHasStaticAttribute.php',
	'PHPUnit\Framework\Constraint\ObjectEquals' => '|8|unit/phpunit/src/Framework/Constraint/Object/ObjectEquals.php',
	'PHPUnit\Framework\Constraint\ObjectHasAttribute' => '|8|unit/phpunit/src/Framework/Constraint/Object/ObjectHasAttribute.php',
	'PHPUnit\Framework\Constraint\BinaryOperator' => '|8|unit/phpunit/src/Framework/Constraint/Operator/BinaryOperator.php',
	'PHPUnit\Framework\Constraint\LogicalAnd' => '|8|unit/phpunit/src/Framework/Constraint/Operator/LogicalAnd.php',
	'PHPUnit\Framework\Constraint\LogicalNot' => '|8|unit/phpunit/src/Framework/Constraint/Operator/LogicalNot.php',
	'PHPUnit\Framework\Constraint\LogicalOr' => '|8|unit/phpunit/src/Framework/Constraint/Operator/LogicalOr.php',
	'PHPUnit\Framework\Constraint\LogicalXor' => '|8|unit/phpunit/src/Framework/Constraint/Operator/LogicalXor.php',
	'PHPUnit\Framework\Constraint\Operator' => '|8|unit/phpunit/src/Framework/Constraint/Operator/Operator.php',
	'PHPUnit\Framework\Constraint\UnaryOperator' => '|8|unit/phpunit/src/Framework/Constraint/Operator/UnaryOperator.php',
	'PHPUnit\Framework\Constraint\IsJson' => '|8|unit/phpunit/src/Framework/Constraint/String/IsJson.php',
	'PHPUnit\Framework\Constraint\RegularExpression' => '|8|unit/phpunit/src/Framework/Constraint/String/RegularExpression.php',
	'PHPUnit\Framework\Constraint\StringContains' => '|8|unit/phpunit/src/Framework/Constraint/String/StringContains.php',
	'PHPUnit\Framework\Constraint\StringEndsWith' => '|8|unit/phpunit/src/Framework/Constraint/String/StringEndsWith.php',
	'PHPUnit\Framework\Constraint\StringMatchesFormatDescription' => '|8|unit/phpunit/src/Framework/Constraint/String/StringMatchesFormatDescription.php',
	'PHPUnit\Framework\Constraint\StringStartsWith' => '|8|unit/phpunit/src/Framework/Constraint/String/StringStartsWith.php',
	'PHPUnit\Framework\Constraint\ArrayHasKey' => '|8|unit/phpunit/src/Framework/Constraint/Traversable/ArrayHasKey.php',
	'PHPUnit\Framework\Constraint\TraversableContains' => '|8|unit/phpunit/src/Framework/Constraint/Traversable/TraversableContains.php',
	'PHPUnit\Framework\Constraint\TraversableContainsEqual' => '|8|unit/phpunit/src/Framework/Constraint/Traversable/TraversableContainsEqual.php',
	'PHPUnit\Framework\Constraint\TraversableContainsIdentical' => '|8|unit/phpunit/src/Framework/Constraint/Traversable/TraversableContainsIdentical.php',
	'PHPUnit\Framework\Constraint\TraversableContainsOnly' => '|8|unit/phpunit/src/Framework/Constraint/Traversable/TraversableContainsOnly.php',
	'PHPUnit\Framework\Constraint\IsInstanceOf' => '|8|unit/phpunit/src/Framework/Constraint/Type/IsInstanceOf.php',
	'PHPUnit\Framework\Constraint\IsNull' => '|8|unit/phpunit/src/Framework/Constraint/Type/IsNull.php',
	'PHPUnit\Framework\Constraint\IsType' => '|8|unit/phpunit/src/Framework/Constraint/Type/IsType.php',
	'PHPUnit\Framework\ActualValueIsNotAnObjectException' => '|8|unit/phpunit/src/Framework/Exception/ActualValueIsNotAnObjectException.php',
	'PHPUnit\Framework\AssertionFailedError' => '|8|unit/phpunit/src/Framework/Exception/AssertionFailedError.php',
	'PHPUnit\Framework\CodeCoverageException' => '|8|unit/phpunit/src/Framework/Exception/CodeCoverageException.php',
	'PHPUnit\Framework\ComparisonMethodDoesNotAcceptParameterTypeException' => '|8|unit/phpunit/src/Framework/Exception/ComparisonMethodDoesNotAcceptParameterTypeException.php',
	'PHPUnit\Framework\ComparisonMethodDoesNotDeclareBoolReturnTypeException' => '|8|unit/phpunit/src/Framework/Exception/ComparisonMethodDoesNotDeclareBoolReturnTypeException.php',
	'PHPUnit\Framework\ComparisonMethodDoesNotDeclareExactlyOneParameterException' => '|8|unit/phpunit/src/Framework/Exception/ComparisonMethodDoesNotDeclareExactlyOneParameterException.php',
	'PHPUnit\Framework\ComparisonMethodDoesNotDeclareParameterTypeException' => '|8|unit/phpunit/src/Framework/Exception/ComparisonMethodDoesNotDeclareParameterTypeException.php',
	'PHPUnit\Framework\ComparisonMethodDoesNotExistException' => '|8|unit/phpunit/src/Framework/Exception/ComparisonMethodDoesNotExistException.php',
	'PHPUnit\Framework\CoveredCodeNotExecutedException' => '|8|unit/phpunit/src/Framework/Exception/CoveredCodeNotExecutedException.php',
	'PHPUnit\Framework\Error' => '|8|unit/phpunit/src/Framework/Exception/Error.php',
	'PHPUnit\Framework\Exception' => '|8|unit/phpunit/src/Framework/Exception/Exception.php',
	'PHPUnit\Framework\ExpectationFailedException' => '|8|unit/phpunit/src/Framework/Exception/ExpectationFailedException.php',
	'PHPUnit\Framework\IncompleteTestError' => '|8|unit/phpunit/src/Framework/Exception/IncompleteTestError.php',
	'PHPUnit\Framework\InvalidArgumentException' => '|8|unit/phpunit/src/Framework/Exception/InvalidArgumentException.php',
	'PHPUnit\Framework\InvalidCoversTargetException' => '|8|unit/phpunit/src/Framework/Exception/InvalidCoversTargetException.php',
	'PHPUnit\Framework\InvalidDataProviderException' => '|8|unit/phpunit/src/Framework/Exception/InvalidDataProviderException.php',
	'PHPUnit\Framework\MissingCoversAnnotationException' => '|8|unit/phpunit/src/Framework/Exception/MissingCoversAnnotationException.php',
	'PHPUnit\Framework\NoChildTestSuiteException' => '|8|unit/phpunit/src/Framework/Exception/NoChildTestSuiteException.php',
	'PHPUnit\Framework\OutputError' => '|8|unit/phpunit/src/Framework/Exception/OutputError.php',
	'PHPUnit\Framework\PHPTAssertionFailedError' => '|8|unit/phpunit/src/Framework/Exception/PHPTAssertionFailedError.php',
	'PHPUnit\Framework\RiskyTestError' => '|8|unit/phpunit/src/Framework/Exception/RiskyTestError.php',
	'PHPUnit\Framework\SkippedTestError' => '|8|unit/phpunit/src/Framework/Exception/SkippedTestError.php',
	'PHPUnit\Framework\SkippedTestSuiteError' => '|8|unit/phpunit/src/Framework/Exception/SkippedTestSuiteError.php',
	'PHPUnit\Framework\SyntheticError' => '|8|unit/phpunit/src/Framework/Exception/SyntheticError.php',
	'PHPUnit\Framework\SyntheticSkippedError' => '|8|unit/phpunit/src/Framework/Exception/SyntheticSkippedError.php',
	'PHPUnit\Framework\UnintentionallyCoveredCodeError' => '|8|unit/phpunit/src/Framework/Exception/UnintentionallyCoveredCodeError.php',
	'PHPUnit\Framework\Warning' => '|8|unit/phpunit/src/Framework/Exception/Warning.php',
	'PHPUnit\Framework\MockObject\ConfigurableMethod' => '|8|unit/phpunit/src/Framework/MockObject/ConfigurableMethod.php',
	'PHPUnit\Framework\MockObject\BadMethodCallException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/BadMethodCallException.php',
	'PHPUnit\Framework\MockObject\CannotUseAddMethodsException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/CannotUseAddMethodsException.php',
	'PHPUnit\Framework\MockObject\CannotUseOnlyMethodsException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/CannotUseOnlyMethodsException.php',
	'PHPUnit\Framework\MockObject\ClassAlreadyExistsException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/ClassAlreadyExistsException.php',
	'PHPUnit\Framework\MockObject\ClassIsFinalException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/ClassIsFinalException.php',
	'PHPUnit\Framework\MockObject\ConfigurableMethodsAlreadyInitializedException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/ConfigurableMethodsAlreadyInitializedException.php',
	'PHPUnit\Framework\MockObject\DuplicateMethodException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/DuplicateMethodException.php',
	'PHPUnit\Framework\MockObject\Exception' => '|8|unit/phpunit/src/Framework/MockObject/Exception/Exception.php',
	'PHPUnit\Framework\MockObject\IncompatibleReturnValueException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/IncompatibleReturnValueException.php',
	'PHPUnit\Framework\MockObject\InvalidMethodNameException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/InvalidMethodNameException.php',
	'PHPUnit\Framework\MockObject\MatchBuilderNotFoundException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/MatchBuilderNotFoundException.php',
	'PHPUnit\Framework\MockObject\MatcherAlreadyRegisteredException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/MatcherAlreadyRegisteredException.php',
	'PHPUnit\Framework\MockObject\MethodCannotBeConfiguredException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/MethodCannotBeConfiguredException.php',
	'PHPUnit\Framework\MockObject\MethodNameAlreadyConfiguredException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/MethodNameAlreadyConfiguredException.php',
	'PHPUnit\Framework\MockObject\MethodNameNotConfiguredException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/MethodNameNotConfiguredException.php',
	'PHPUnit\Framework\MockObject\MethodParametersAlreadyConfiguredException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/MethodParametersAlreadyConfiguredException.php',
	'PHPUnit\Framework\MockObject\OriginalConstructorInvocationRequiredException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/OriginalConstructorInvocationRequiredException.php',
	'PHPUnit\Framework\MockObject\ReflectionException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/ReflectionException.php',
	'PHPUnit\Framework\MockObject\ReturnValueNotConfiguredException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/ReturnValueNotConfiguredException.php',
	'PHPUnit\Framework\MockObject\RuntimeException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/RuntimeException.php',
	'PHPUnit\Framework\MockObject\SoapExtensionNotAvailableException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/SoapExtensionNotAvailableException.php',
	'PHPUnit\Framework\MockObject\UnknownClassException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/UnknownClassException.php',
	'PHPUnit\Framework\MockObject\UnknownTraitException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/UnknownTraitException.php',
	'PHPUnit\Framework\MockObject\UnknownTypeException' => '|8|unit/phpunit/src/Framework/MockObject/Exception/UnknownTypeException.php',
	'PHPUnit\Framework\MockObject\Generator' => '|8|unit/phpunit/src/Framework/MockObject/Generator.php',
	'PHPUnit\Framework\MockObject\Invocation' => '|8|unit/phpunit/src/Framework/MockObject/Invocation.php',
	'PHPUnit\Framework\MockObject\InvocationHandler' => '|8|unit/phpunit/src/Framework/MockObject/InvocationHandler.php',
	'PHPUnit\Framework\MockObject\Matcher' => '|8|unit/phpunit/src/Framework/MockObject/Matcher.php',
	'PHPUnit\Framework\MockObject\MethodNameConstraint' => '|8|unit/phpunit/src/Framework/MockObject/MethodNameConstraint.php',
	'PHPUnit\Framework\MockObject\MockBuilder' => '|8|unit/phpunit/src/Framework/MockObject/MockBuilder.php',
	'PHPUnit\Framework\MockObject\MockClass' => '|8|unit/phpunit/src/Framework/MockObject/MockClass.php',
	'PHPUnit\Framework\MockObject\MockMethod' => '|8|unit/phpunit/src/Framework/MockObject/MockMethod.php',
	'PHPUnit\Framework\MockObject\MockMethodSet' => '|8|unit/phpunit/src/Framework/MockObject/MockMethodSet.php',
	'PHPUnit\Framework\MockObject\MockObject' => '|8|unit/phpunit/src/Framework/MockObject/MockObject.php',
	'PHPUnit\Framework\MockObject\MockTrait' => '|8|unit/phpunit/src/Framework/MockObject/MockTrait.php',
	'PHPUnit\Framework\MockObject\MockType' => '|8|unit/phpunit/src/Framework/MockObject/MockType.php',
	'PHPUnit\Framework\MockObject\Stub' => '|8|unit/phpunit/src/Framework/MockObject/Stub.php',
	'PHPUnit\Framework\MockObject\Verifiable' => '|8|unit/phpunit/src/Framework/MockObject/Verifiable.php',
	'PHPUnit\Runner\AfterIncompleteTestHook' => '|8|unit/phpunit/src/Runner/Hook/AfterIncompleteTestHook.php',
	'PHPUnit\Runner\AfterLastTestHook' => '|8|unit/phpunit/src/Runner/Hook/AfterLastTestHook.php',
	'PHPUnit\Runner\AfterRiskyTestHook' => '|8|unit/phpunit/src/Runner/Hook/AfterRiskyTestHook.php',
	'PHPUnit\Runner\AfterSkippedTestHook' => '|8|unit/phpunit/src/Runner/Hook/AfterSkippedTestHook.php',
	'PHPUnit\Runner\AfterSuccessfulTestHook' => '|8|unit/phpunit/src/Runner/Hook/AfterSuccessfulTestHook.php',
	'PHPUnit\Runner\AfterTestErrorHook' => '|8|unit/phpunit/src/Runner/Hook/AfterTestErrorHook.php',
	'PHPUnit\Runner\AfterTestFailureHook' => '|8|unit/phpunit/src/Runner/Hook/AfterTestFailureHook.php',
	'PHPUnit\Runner\AfterTestHook' => '|8|unit/phpunit/src/Runner/Hook/AfterTestHook.php',
	'PHPUnit\Runner\AfterTestWarningHook' => '|8|unit/phpunit/src/Runner/Hook/AfterTestWarningHook.php',
	'PHPUnit\Runner\BeforeFirstTestHook' => '|8|unit/phpunit/src/Runner/Hook/BeforeFirstTestHook.php',
	'PHPUnit\Runner\BeforeTestHook' => '|8|unit/phpunit/src/Runner/Hook/BeforeTestHook.php',
	'PHPUnit\Runner\Hook' => '|8|unit/phpunit/src/Runner/Hook/Hook.php',
	'PHPUnit\Runner\TestHook' => '|8|unit/phpunit/src/Runner/Hook/TestHook.php',
	'PHPUnit\Runner\TestListenerAdapter' => '|8|unit/phpunit/src/Runner/Hook/TestListenerAdapter.php',
	'PHPUnit\TextUI\Exception' => '|8|unit/phpunit/src/TextUI/Exception/Exception.php',
	'PHPUnit\TextUI\ReflectionException' => '|8|unit/phpunit/src/TextUI/Exception/ReflectionException.php',
	'PHPUnit\TextUI\RuntimeException' => '|8|unit/phpunit/src/TextUI/Exception/RuntimeException.php',
	'PHPUnit\TextUI\TestDirectoryNotFoundException' => '|8|unit/phpunit/src/TextUI/Exception/TestDirectoryNotFoundException.php',
	'PHPUnit\TextUI\TestFileNotFoundException' => '|8|unit/phpunit/src/TextUI/Exception/TestFileNotFoundException.php',
	'PHPUnit\TextUI\XmlConfiguration\Directory' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Filesystem/Directory.php',
	'PHPUnit\TextUI\XmlConfiguration\DirectoryCollection' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Filesystem/DirectoryCollection.php',
	'PHPUnit\TextUI\XmlConfiguration\DirectoryCollectionIterator' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Filesystem/DirectoryCollectionIterator.php',
	'PHPUnit\TextUI\XmlConfiguration\File' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Filesystem/File.php',
	'PHPUnit\TextUI\XmlConfiguration\FileCollection' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Filesystem/FileCollection.php',
	'PHPUnit\TextUI\XmlConfiguration\FileCollectionIterator' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Filesystem/FileCollectionIterator.php',
	'PHPUnit\TextUI\XmlConfiguration\Group' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Group/Group.php',
	'PHPUnit\TextUI\XmlConfiguration\GroupCollection' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Group/GroupCollection.php',
	'PHPUnit\TextUI\XmlConfiguration\GroupCollectionIterator' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Group/GroupCollectionIterator.php',
	'PHPUnit\TextUI\XmlConfiguration\Groups' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Group/Groups.php',
	'PHPUnit\TextUI\XmlConfiguration\MigrationBuilder' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/MigrationBuilder.php',
	'PHPUnit\TextUI\XmlConfiguration\MigrationBuilderException' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/MigrationBuilderException.php',
	'PHPUnit\TextUI\XmlConfiguration\MigrationException' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/MigrationException.php',
	'PHPUnit\TextUI\XmlConfiguration\ConvertLogTypes' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/ConvertLogTypes.php',
	'PHPUnit\TextUI\XmlConfiguration\CoverageCloverToReport' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/CoverageCloverToReport.php',
	'PHPUnit\TextUI\XmlConfiguration\CoverageCrap4jToReport' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/CoverageCrap4jToReport.php',
	'PHPUnit\TextUI\XmlConfiguration\CoverageHtmlToReport' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/CoverageHtmlToReport.php',
	'PHPUnit\TextUI\XmlConfiguration\CoveragePhpToReport' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/CoveragePhpToReport.php',
	'PHPUnit\TextUI\XmlConfiguration\CoverageTextToReport' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/CoverageTextToReport.php',
	'PHPUnit\TextUI\XmlConfiguration\CoverageXmlToReport' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/CoverageXmlToReport.php',
	'PHPUnit\TextUI\XmlConfiguration\IntroduceCoverageElement' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/IntroduceCoverageElement.php',
	'PHPUnit\TextUI\XmlConfiguration\LogToReportMigration' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/LogToReportMigration.php',
	'PHPUnit\TextUI\XmlConfiguration\Migration' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/Migration.php',
	'PHPUnit\TextUI\XmlConfiguration\MoveAttributesFromFilterWhitelistToCoverage' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/MoveAttributesFromFilterWhitelistToCoverage.php',
	'PHPUnit\TextUI\XmlConfiguration\MoveAttributesFromRootToCoverage' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/MoveAttributesFromRootToCoverage.php',
	'PHPUnit\TextUI\XmlConfiguration\MoveWhitelistDirectoriesToCoverage' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/MoveWhitelistDirectoriesToCoverage.php',
	'PHPUnit\TextUI\XmlConfiguration\MoveWhitelistExcludesToCoverage' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/MoveWhitelistExcludesToCoverage.php',
	'PHPUnit\TextUI\XmlConfiguration\RemoveCacheTokensAttribute' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/RemoveCacheTokensAttribute.php',
	'PHPUnit\TextUI\XmlConfiguration\RemoveEmptyFilter' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/RemoveEmptyFilter.php',
	'PHPUnit\TextUI\XmlConfiguration\RemoveLogTypes' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/RemoveLogTypes.php',
	'PHPUnit\TextUI\XmlConfiguration\UpdateSchemaLocationTo93' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrations/UpdateSchemaLocationTo93.php',
	'PHPUnit\TextUI\XmlConfiguration\Migrator' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/Migration/Migrator.php',
	'PHPUnit\TextUI\XmlConfiguration\Constant' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHP/Constant.php',
	'PHPUnit\TextUI\XmlConfiguration\ConstantCollection' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHP/ConstantCollection.php',
	'PHPUnit\TextUI\XmlConfiguration\ConstantCollectionIterator' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHP/ConstantCollectionIterator.php',
	'PHPUnit\TextUI\XmlConfiguration\IniSetting' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHP/IniSetting.php',
	'PHPUnit\TextUI\XmlConfiguration\IniSettingCollection' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHP/IniSettingCollection.php',
	'PHPUnit\TextUI\XmlConfiguration\IniSettingCollectionIterator' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHP/IniSettingCollectionIterator.php',
	'PHPUnit\TextUI\XmlConfiguration\Php' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHP/Php.php',
	'PHPUnit\TextUI\XmlConfiguration\PhpHandler' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHP/PhpHandler.php',
	'PHPUnit\TextUI\XmlConfiguration\Variable' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHP/Variable.php',
	'PHPUnit\TextUI\XmlConfiguration\VariableCollection' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHP/VariableCollection.php',
	'PHPUnit\TextUI\XmlConfiguration\VariableCollectionIterator' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHP/VariableCollectionIterator.php',
	'PHPUnit\TextUI\XmlConfiguration\Extension' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHPUnit/Extension.php',
	'PHPUnit\TextUI\XmlConfiguration\ExtensionCollection' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHPUnit/ExtensionCollection.php',
	'PHPUnit\TextUI\XmlConfiguration\ExtensionCollectionIterator' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHPUnit/ExtensionCollectionIterator.php',
	'PHPUnit\TextUI\XmlConfiguration\PHPUnit' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/PHPUnit/PHPUnit.php',
	'PHPUnit\TextUI\XmlConfiguration\TestDirectory' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestDirectory.php',
	'PHPUnit\TextUI\XmlConfiguration\TestDirectoryCollection' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestDirectoryCollection.php',
	'PHPUnit\TextUI\XmlConfiguration\TestDirectoryCollectionIterator' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestDirectoryCollectionIterator.php',
	'PHPUnit\TextUI\XmlConfiguration\TestFile' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestFile.php',
	'PHPUnit\TextUI\XmlConfiguration\TestFileCollection' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestFileCollection.php',
	'PHPUnit\TextUI\XmlConfiguration\TestFileCollectionIterator' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestFileCollectionIterator.php',
	'PHPUnit\TextUI\XmlConfiguration\TestSuite' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestSuite.php',
	'PHPUnit\TextUI\XmlConfiguration\TestSuiteCollection' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestSuiteCollection.php',
	'PHPUnit\TextUI\XmlConfiguration\TestSuiteCollectionIterator' => '|8|unit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestSuiteCollectionIterator.php',
	'SebastianBergmann\CliParser\AmbiguousOptionException' => '|9|AmbiguousOptionException.php',
	'SebastianBergmann\CliParser\Exception' => '|9|Exception.php',
	'SebastianBergmann\CliParser\OptionDoesNotAllowArgumentException' => '|9|OptionDoesNotAllowArgumentException.php',
	'SebastianBergmann\CliParser\RequiredOptionArgumentMissingException' => '|9|RequiredOptionArgumentMissingException.php',
	'SebastianBergmann\CliParser\UnknownOptionException' => '|9|UnknownOptionException.php',
	'SebastianBergmann\CodeUnit\Exception' => '|10|ode-unit/src/exceptions/Exception.php',
	'SebastianBergmann\CodeUnit\InvalidCodeUnitException' => '|10|ode-unit/src/exceptions/InvalidCodeUnitException.php',
	'SebastianBergmann\CodeUnit\NoTraitException' => '|10|ode-unit/src/exceptions/NoTraitException.php',
	'SebastianBergmann\CodeUnit\ReflectionException' => '|10|ode-unit/src/exceptions/ReflectionException.php',
	'SebastianBergmann\Comparator\Exception' => '|10|omparator/src/exceptions/Exception.php',
	'SebastianBergmann\Comparator\RuntimeException' => '|10|omparator/src/exceptions/RuntimeException.php',
	'SebastianBergmann\Complexity\Complexity' => '|10|omplexity/src/Complexity/Complexity.php',
	'SebastianBergmann\Complexity\ComplexityCollection' => '|10|omplexity/src/Complexity/ComplexityCollection.php',
	'SebastianBergmann\Complexity\ComplexityCollectionIterator' => '|10|omplexity/src/Complexity/ComplexityCollectionIterator.php',
	'SebastianBergmann\Complexity\Exception' => '|10|omplexity/src/Exception/Exception.php',
	'SebastianBergmann\Complexity\RuntimeException' => '|10|omplexity/src/Exception/RuntimeException.php',
	'SebastianBergmann\Complexity\ComplexityCalculatingVisitor' => '|10|omplexity/src/Visitor/ComplexityCalculatingVisitor.php',
	'SebastianBergmann\Complexity\CyclomaticComplexityCalculatingVisitor' => '|10|omplexity/src/Visitor/CyclomaticComplexityCalculatingVisitor.php',
	'SebastianBergmann\Diff\ConfigurationException' => '|11|diff/src/Exception/ConfigurationException.php',
	'SebastianBergmann\Diff\Exception' => '|11|diff/src/Exception/Exception.php',
	'SebastianBergmann\Diff\InvalidArgumentException' => '|11|diff/src/Exception/InvalidArgumentException.php',
	'SebastianBergmann\GlobalState\Exception' => '|11|global-state/src/exceptions/Exception.php',
	'SebastianBergmann\GlobalState\RuntimeException' => '|11|global-state/src/exceptions/RuntimeException.php',
	'SebastianBergmann\LinesOfCode\Exception' => '|11|lines-of-code/src/Exception/Exception.php',
	'SebastianBergmann\LinesOfCode\IllogicalValuesException' => '|11|lines-of-code/src/Exception/IllogicalValuesException.php',
	'SebastianBergmann\LinesOfCode\NegativeValueException' => '|11|lines-of-code/src/Exception/NegativeValueException.php',
	'SebastianBergmann\LinesOfCode\RuntimeException' => '|11|lines-of-code/src/Exception/RuntimeException.php',
	'SebastianBergmann\Type\Exception' => '|11|type/src/exception/Exception.php',
	'SebastianBergmann\Type\RuntimeException' => '|11|type/src/exception/RuntimeException.php',
	'SebastianBergmann\Type\CallableType' => '|11|type/src/type/CallableType.php',
	'SebastianBergmann\Type\FalseType' => '|11|type/src/type/FalseType.php',
	'SebastianBergmann\Type\GenericObjectType' => '|11|type/src/type/GenericObjectType.php',
	'SebastianBergmann\Type\IntersectionType' => '|11|type/src/type/IntersectionType.php',
	'SebastianBergmann\Type\IterableType' => '|11|type/src/type/IterableType.php',
	'SebastianBergmann\Type\MixedType' => '|11|type/src/type/MixedType.php',
	'SebastianBergmann\Type\NeverType' => '|11|type/src/type/NeverType.php',
	'SebastianBergmann\Type\NullType' => '|11|type/src/type/NullType.php',
	'SebastianBergmann\Type\ObjectType' => '|11|type/src/type/ObjectType.php',
	'SebastianBergmann\Type\SimpleType' => '|11|type/src/type/SimpleType.php',
	'SebastianBergmann\Type\StaticType' => '|11|type/src/type/StaticType.php',
	'SebastianBergmann\Type\Type' => '|11|type/src/type/Type.php',
	'SebastianBergmann\Type\UnionType' => '|11|type/src/type/UnionType.php',
	'SebastianBergmann\Type\UnknownType' => '|11|type/src/type/UnknownType.php',
	'SebastianBergmann\Type\VoidType' => '|11|type/src/type/VoidType.php'
];
$s627ba192388d7__arrautoloadCustomCommon = [
	1 => '/vendor/composer/autoload_',
	2 => '/vendor/klein/klein/tests/Klein/Tests/',
	3 => '/vendor/phar-io/manifest/src/exceptions/E',
	4 => '/vendor/phar-io/manifest/src/exceptions/',
	5 => '/vendor/phar-io/manifest/src/',
	6 => '/vendor/phar-io/',
	7 => '/vendor/phpdocumentor/reflection-docblock/src/DocBlock',
	8 => '/vendor/php',
	9 => '/vendor/sebastian/cli-parser/src/exceptions/',
	10 => '/vendor/sebastian/c',
	11 => '/vendor/sebastian/'
];

/* @var string[] Where $_arrautoload['namespace']='folder' */
$s627ba192388d7__arrautoload = [
	'DS' => '.',
	'Composer\Autoload' => '|1|',
	'Composer' => '|1|',
	'Doctrine\Instantiator\Exception' => '|2|/Exception',
	'Doctrine\Instantiator' => '|2|',
	'eftec\bladeone' => '/vendor/eftec/bladeone/lib',
	'Klein' => '|3|',
	'Klein\DataCollection' => '|3|/DataCollection',
	'Klein\Exceptions' => '|3|/Exceptions',
	'Klein\Tests' => '|4|tests/Klein/Tests',
	'Klein\Tests\DataCollection' => '|4|tests/Klein/Tests/DataCollection',
	'Klein\Tests\Mocks' => '|4|tests/Klein/Tests/Mocks',
	'DeepCopy' => '|5|',
	'DeepCopy\Exception' => '|5|/Exception',
	'DeepCopy\Filter\Doctrine' => '|5|/Filter/Doctrine',
	'DeepCopy\Filter' => '|5|/Filter',
	'DeepCopy\Matcher\Doctrine' => '|5|/Matcher/Doctrine',
	'DeepCopy\Matcher' => '|5|/Matcher',
	'DeepCopy\Reflection' => '|5|/Reflection',
	'DeepCopy\TypeFilter\Date' => '|5|/TypeFilter/Date',
	'DeepCopy\TypeFilter' => '|5|/TypeFilter',
	'DeepCopy\TypeFilter\Spl' => '|5|/TypeFilter/Spl',
	'DeepCopy\TypeMatcher' => '|5|/TypeMatcher',
	'PhpParser\Builder' => '|6|Builder',
	'PhpParser' => '/vendor/nikic/php-parser/lib/PhpParser',
	'PhpParser\Comment' => '|6|Comment',
	'PhpParser\ErrorHandler' => '|6|ErrorHandler',
	'PhpParser\Internal' => '|6|Internal',
	'PhpParser\Lexer' => '|6|Lexer',
	'PhpParser\Lexer\TokenEmulator' => '|6|Lexer/TokenEmulator',
	'PhpParser\Node' => '|6|Node',
	'PhpParser\Node\Expr' => '|6|Node/Expr',
	'PhpParser\Node\Expr\AssignOp' => '|6|Node/Expr/AssignOp',
	'PhpParser\Node\Expr\BinaryOp' => '|6|Node/Expr/BinaryOp',
	'PhpParser\Node\Expr\Cast' => '|6|Node/Expr/Cast',
	'PhpParser\Node\Name' => '|6|Node/Name',
	'PhpParser\Node\Scalar' => '|6|Node/Scalar',
	'PhpParser\Node\Scalar\MagicConst' => '|6|Node/Scalar/MagicConst',
	'PhpParser\Node\Stmt' => '|6|Node/Stmt',
	'PhpParser\Node\Stmt\TraitUseAdaptation' => '|6|Node/Stmt/TraitUseAdaptation',
	'PhpParser\NodeVisitor' => '|6|NodeVisitor',
	'PhpParser\Parser' => '|6|Parser',
	'PhpParser\PrettyPrinter' => '|6|PrettyPrinter',
	'PharIo\Manifest' => '|7|manifest/src',
	'PharIo\Version' => '|7|version/src',
	'phpDocumentor\Reflection' => '|8|common/src',
	'phpDocumentor\Reflection\DocBlock' => '|8|docblock/src/DocBlock',
	'phpDocumentor\Reflection\DocBlock\Tags' => '|8|docblock/src/DocBlock/Tags',
	'phpDocumentor\Reflection\DocBlock\Tags\Factory' => '|8|docblock/src/DocBlock/Tags/Factory',
	'phpDocumentor\Reflection\DocBlock\Tags\Formatter' => '|8|docblock/src/DocBlock/Tags/Formatter',
	'phpDocumentor\Reflection\DocBlock\Tags\Reference' => '|8|docblock/src/DocBlock/Tags/Reference',
	'phpDocumentor\Reflection\Exception' => '|8|docblock/src/Exception',
	'phpDocumentor\Reflection\PseudoTypes' => '|9|documentor/type-resolver/src/PseudoTypes',
	'phpDocumentor\Reflection\Types' => '|9|documentor/type-resolver/src/Types',
	'Prophecy\Argument' => '|9|spec/prophecy/src/Prophecy/Argument',
	'Prophecy\Argument\Token' => '|9|spec/prophecy/src/Prophecy/Argument/Token',
	'Prophecy' => '|9|spec/prophecy/src/Prophecy',
	'Prophecy\Call' => '|9|spec/prophecy/src/Prophecy/Call',
	'Prophecy\Comparator' => '|9|spec/prophecy/src/Prophecy/Comparator',
	'Prophecy\Doubler' => '|9|spec/prophecy/src/Prophecy/Doubler',
	'Prophecy\Doubler\ClassPatch' => '|9|spec/prophecy/src/Prophecy/Doubler/ClassPatch',
	'Prophecy\Doubler\Generator' => '|9|spec/prophecy/src/Prophecy/Doubler/Generator',
	'Prophecy\Doubler\Generator\Node' => '|9|spec/prophecy/src/Prophecy/Doubler/Generator/Node',
	'Prophecy\Exception\Call' => '|9|spec/prophecy/src/Prophecy/Exception/Call',
	'Prophecy\Exception\Doubler' => '|9|spec/prophecy/src/Prophecy/Exception/Doubler',
	'Prophecy\Exception' => '|9|spec/prophecy/src/Prophecy/Exception',
	'Prophecy\Exception\Prediction' => '|9|spec/prophecy/src/Prophecy/Exception/Prediction',
	'Prophecy\Exception\Prophecy' => '|9|spec/prophecy/src/Prophecy/Exception/Prophecy',
	'Prophecy\PhpDocumentor' => '|9|spec/prophecy/src/Prophecy/PhpDocumentor',
	'Prophecy\Prediction' => '|9|spec/prophecy/src/Prophecy/Prediction',
	'Prophecy\Promise' => '|9|spec/prophecy/src/Prophecy/Promise',
	'Prophecy\Prophecy' => '|9|spec/prophecy/src/Prophecy/Prophecy',
	'Prophecy\Util' => '|9|spec/prophecy/src/Prophecy/Util',
	'SebastianBergmann\CodeCoverage' => '|9|unit/php-code-coverage/src',
	'SebastianBergmann\CodeCoverage\Driver' => '|9|unit/php-code-coverage/src/Driver',
	'SebastianBergmann\CodeCoverage\Util' => '|9|unit/php-code-coverage/src/Exception',
	'SebastianBergmann\CodeCoverage\Node' => '|9|unit/php-code-coverage/src/Node',
	'SebastianBergmann\CodeCoverage\Report' => '|9|unit/php-code-coverage/src/Report',
	'SebastianBergmann\CodeCoverage\Report\Html' => '|9|unit/php-code-coverage/src/Report/Html',
	'SebastianBergmann\CodeCoverage\Report\Xml' => '|9|unit/php-code-coverage/src/Report/Xml',
	'SebastianBergmann\CodeCoverage\StaticAnalysis' => '|9|unit/php-code-coverage/src/StaticAnalysis',
	'SebastianBergmann\FileIterator' => '|9|unit/php-file-iterator/src',
	'SebastianBergmann\Invoker' => '|9|unit/php-invoker/src',
	'SebastianBergmann\Template' => '|9|unit/php-text-template/src',
	'SebastianBergmann\Timer' => '|9|unit/php-timer/src',
	'PHPUnit' => '|9|unit/phpunit/src',
	'PHPUnit\Framework' => '|9|unit/phpunit/src/Framework',
	'PHPUnit\Framework\Constraint' => '|9|unit/phpunit/src/Framework/Constraint/Boolean',
	'PHPUnit\Framework\Error' => '|9|unit/phpunit/src/Framework/Error',
	'PHPUnit\Framework\MockObject' => '|9|unit/phpunit/src/Framework/MockObject/Api',
	'PHPUnit\Framework\MockObject\Builder' => '|9|unit/phpunit/src/Framework/MockObject/Builder',
	'PHPUnit\Framework\MockObject\Rule' => '|9|unit/phpunit/src/Framework/MockObject/Rule',
	'PHPUnit\Framework\MockObject\Stub' => '|9|unit/phpunit/src/Framework/MockObject/Stub',
	'PHPUnit\Runner' => '|9|unit/phpunit/src/Runner',
	'PHPUnit\Runner\Extension' => '|9|unit/phpunit/src/Runner/Extension',
	'PHPUnit\Runner\Filter' => '|9|unit/phpunit/src/Runner/Filter',
	'PHPUnit\TextUI\CliArguments' => '|9|unit/phpunit/src/TextUI/CliArguments',
	'PHPUnit\TextUI' => '|9|unit/phpunit/src/TextUI',
	'PHPUnit\TextUI\XmlConfiguration\CodeCoverage' => '|9|unit/phpunit/src/TextUI/XmlConfiguration/CodeCoverage',
	'PHPUnit\TextUI\XmlConfiguration\CodeCoverage\Filter' => '|9|unit/phpunit/src/TextUI/XmlConfiguration/CodeCoverage/Filter',
	'PHPUnit\TextUI\XmlConfiguration\CodeCoverage\Report' => '|9|unit/phpunit/src/TextUI/XmlConfiguration/CodeCoverage/Report',
	'PHPUnit\TextUI\XmlConfiguration' => '|9|unit/phpunit/src/TextUI/XmlConfiguration',
	'PHPUnit\TextUI\XmlConfiguration\Logging' => '|9|unit/phpunit/src/TextUI/XmlConfiguration/Logging',
	'PHPUnit\TextUI\XmlConfiguration\Logging\TestDox' => '|9|unit/phpunit/src/TextUI/XmlConfiguration/Logging/TestDox',
	'PHPUnit\Util\Annotation' => '|9|unit/phpunit/src/Util/Annotation',
	'PHPUnit\Util' => '|9|unit/phpunit/src/Util',
	'PHPUnit\Util\Log' => '|9|unit/phpunit/src/Util/Log',
	'PHPUnit\Util\PHP' => '|9|unit/phpunit/src/Util/PHP',
	'PHPUnit\Util\TestDox' => '|9|unit/phpunit/src/Util/TestDox',
	'PHPUnit\Util\Xml' => '|9|unit/phpunit/src/Util/Xml',
	'SebastianBergmann\CliParser' => '|10|li-parser/src',
	'SebastianBergmann\CodeUnit' => '|10|ode-unit/src',
	'SebastianBergmann\CodeUnitReverseLookup' => '|10|ode-unit-reverse-lookup/src',
	'SebastianBergmann\Comparator' => '|10|omparator/src',
	'SebastianBergmann\Complexity' => '|10|omplexity/src',
	'SebastianBergmann\Diff' => '|11|diff/src',
	'SebastianBergmann\Diff\Output' => '|11|diff/src/Output',
	'SebastianBergmann\Environment' => '|11|environment/src',
	'SebastianBergmann\Exporter' => '|11|exporter/src',
	'SebastianBergmann\GlobalState' => '|11|global-state/src',
	'SebastianBergmann\LinesOfCode' => '|11|lines-of-code/src',
	'SebastianBergmann\ObjectEnumerator' => '|11|object-enumerator/src',
	'SebastianBergmann\ObjectReflector' => '|11|object-reflector/src',
	'SebastianBergmann\RecursionContext' => '|11|recursion-context/src',
	'SebastianBergmann\ResourceOperations' => '|11|resource-operations/src',
	'SebastianBergmann\Type' => '|11|type/src',
	'SebastianBergmann' => '|11|version/src',
	'Symfony\Polyfill\Ctype' => '/vendor/symfony/polyfill-ctype',
	'TheSeer\Tokenizer' => '/vendor/theseer/tokenizer/src',
	'Webmozart\Assert' => '/vendor/webmozart/assert/src'
];
$s627ba192388d7__arrautoloadCommon = [
	1 => '/vendor/composer',
	2 => '/vendor/doctrine/instantiator/src/Doctrine/Instantiator',
	3 => '/vendor/klein/klein/src/Klein',
	4 => '/vendor/klein/klein/',
	5 => '/vendor/myclabs/deep-copy/src/DeepCopy',
	6 => '/vendor/nikic/php-parser/lib/PhpParser/',
	7 => '/vendor/phar-io/',
	8 => '/vendor/phpdocumentor/reflection-',
	9 => '/vendor/php',
	10 => '/vendor/sebastian/c',
	11 => '/vendor/sebastian/'
];

/* @var boolean[] Where $_arrautoload['namespace' or 'namespace\Class']=true if it's absolute (it uses the full path) */
$s627ba192388d7__arrautoloadAbsolute = [
 
];

/**
 * @param $class_name
 * @throws Exception
 */
function s627ba192388d7__auto($class_name)
{
    // its called only if the class is not loaded.
    set_exception_handler('autoloadone_exception_handler');
    $p=strrpos($class_name,'\\');
    if($p!==false) {
        $ns=substr($class_name,0,$p);
        $cls=substr($class_name,$p+1);
    } else {
        $ns='';
        $cls=$class_name;
    }
    // special cases
    if (isset($GLOBALS['s627ba192388d7__arrautoloadCustom'][$class_name])) {
        s627ba192388d7__loadIfExists($class_name,$GLOBALS['s627ba192388d7__arrautoloadCustom'][$class_name]
            , $class_name,'s627ba192388d7__arrautoloadCustomCommon');
        restore_exception_handler();
        return;
    }
    // normal (folder) cases
    if (isset($GLOBALS['s627ba192388d7__arrautoload'][$ns])) {
        s627ba192388d7__loadIfExists($class_name,$GLOBALS['s627ba192388d7__arrautoload'][$ns] . '/' . $cls . '.php'
            , $ns,'s627ba192388d7__arrautoloadCommon');
        restore_exception_handler();
        return;
    }
    if(!class_exists($class_name)) {
        throw new RuntimeException("AutoLoadOne Error: No file found for class [$class_name]");
    }
    restore_exception_handler();    
}

/**
 * We load the file.    
 * @param string $className the name of the class
 * @param string $filename the filename to load
 * @param string $key key of the class it could be the full class name or only the namespace
 * @param string $arrayName [optional] it's the name of the arrayname used to replaced |n| values. 
 * @throws Exception
 */
function s627ba192388d7__loadIfExists($className,$filename, $key,$arrayName='')
{
    if (isset($GLOBALS['s627ba192388d7__arrautoloadAbsolute'][$key])) {
        $fullFile = $filename; // its an absolute path
        if (strpos($fullFile, '../') === 0) { // Or maybe, not, it's a remote-relative path.
            $oldDir = getcwd();  // we copy the current url
            chdir(__DIR__);
        }
    } else {
        $fullFile = __DIR__ . '/' . s627ba192388d7__replaceCurlyVariable($filename, $arrayName); // its relative to this path
    }
    /** @noinspection PhpIncludeInspection */
    if ((@include $fullFile) === false) {
        if ($GLOBALS['autoloadone__debug']) {
            throw new RuntimeException("AutoLoadOne Error: Loading file [$fullFile] for class [$className]");
        }
        throw new RuntimeException("AutoLoadOne Error: No file found for class [$className]");
    }
    if (isset($oldDir)) {
        chdir($oldDir);
    }
} 
function s627ba192388d7__replaceCurlyVariable($string,$arrayName) {
    if(strpos($string,'|')===false) {
        return $string;
    } // nothing to replace.
    return preg_replace_callback('/\\|\s?(\w+)\s?\\|/u', static function ($matches) use ($arrayName) {
        $item = is_array($matches) ? substr($matches[0], 1, -1)
            : substr($matches, 1, -1);
        return $GLOBALS[$arrayName][$item];
    }, $string);
}
function autoloadone_exception_handler($exception) {
    $isCli=!http_response_code();
    $r="Uncaught Exception: [".get_class($exception)."] code:".$exception->getCode()."\n".$exception->getMessage()."\n";
    if ($GLOBALS['autoloadone__debug']) {
        $r .= "Trace:\n";
        foreach ($exception->getTrace() as $error) {
            // we remove all trace pointing to this file.
            if (isset($error['file'])) {
                if(strpos($error['file'], __FILE__) === false) {
                    $r .= @$error['file'] . '[' . @$error['line'] . ']' . ' function:' . @$error['function'] . '('
                        .( is_array(@$error['args']) ? @implode(',', @$error['args']) . ')' :@$error['args'])
                        . "\n";
                } else {
                    $r .= '(nofile)' . '[' . @$error['line'] . ']' . ' function:' . @$error['function'] . '('
                        .( is_array(@$error['args']) ? @implode(',', @$error['args']) . ')' :@$error['args'])
                        . "\n";                
                }
            }
        }
    }
    if(!$isCli) {
        $r=str_replace(["\n",'[',']'],["<br>","<b>[","]</b>"],$r);
    }
    echo $r;
    die(1);
}



spl_autoload_register(static function ($class_name) {
    s627ba192388d7__auto($class_name);
});
// Autorun: this file was created using _AUTOLOAD_COMPOSERJSON=false so autorun is disabled

